# Generated by Django 4.2.8 on 2023-12-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanmodel',
            name='provider',
        ),
    ]
