# Generated by Django 4.2.8 on 2023-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_loanmodel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='amount_paid',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='amount_to_pay',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='total_amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
