# Generated by Django 4.2.8 on 2023-12-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanschema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanschemamodel',
            name='bank_percentage',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
