# Generated by Django 4.2.8 on 2023-12-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_options_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='national_id',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
