# Generated by Django 4.2.8 on 2023-12-20 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_usermodel_name_alter_usermodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProviderModel',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_total_funds', models.DecimalField(decimal_places=5, max_digits=25)),
            ],
        ),
    ]
