# Generated by Django 4.2.8 on 2023-12-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_provider', '0001_initial'),
        ('fund', '0002_alter_loanmodel_provider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanModel',
            new_name='FundModel',
        ),
    ]
